const tradingTips = [
  "💡 Tip: Don’t trade your bias — trade the chart.",
  "📈 Momentum: The trend is your friend until it bends.",
  "⚠️ Risk: Never risk more than you’re willing to lose.",
  "🧠 Mindset: Emotional control is your real edge.",
  "📝 Journal: Review your trades — the market is your best teacher.",
  "✅ Plan: Enter with a reason. Exit with a plan.",
  "🧘 Discipline: Patience pays more than prediction.",
  "📊 Data: Let statistics, not emotions, drive decisions.",
  "🔒 Capital: Protect your capital — it’s your ammo.",
  "⏳ Timing: No position is better than a bad one.",
  "🎯 Focus: One solid setup beats five forced trades.",
  "🔁 Cycle: If you keep making the same mistake — pause and adjust.",
  "🔍 Analysis: Price + context > indicators alone.",
  "🧱 Foundation: Master one strategy before chasing another.",
  "📌 Reminder: Consistency is a skill — train it daily.",
  "🧭 Direction: Wait for confirmation, not just assumption.",
  "🦍 Humor: FOMO makes you the liquidity — not the winner.",
  "🧃 Discipline: Don’t let boredom be your entry signal.",
  "💣 Stop Loss: A stop loss is strategy, not fear.",
  "🧊 Control: Cool heads last longer in hot markets.",
  "📉 Tip: Cutting losers fast is as important as letting winners run.",
  "💹 Scalping: Fast moves ≠ good trades — measure risk.",
  "🛑 Mistake: A losing trade ≠ a bad trade if you followed your plan.",
  "👁️ Visual: Clean charts → clean thinking.",
  "🐢 Reminder: Slow and steady often wins the account.",
  "🔄 Adapt: Market conditions change. So should your strategy.",
  "🎯 Sniper: Be precise — don’t spray and pray.",
  "⚔️ Mental Game: Your biggest opponent is your own impatience.",
  "💼 Professional: Treat trading like a business, not a lottery.",
  "📆 Daily Tip: Review your performance weekly, not just your PnL.",
  "🛠️ Setup: Tools are useless without a system.",
  "🎬 Execution: Good analysis is wasted by poor execution.",
  "🧮 Size: Right idea, wrong size = wrong result.",
  "🔔 News: Always be aware of major economic events.",
  "🧬 Repeat: Systems only work if you repeat them.",
  "📦 Strategy: Simplicity is scalable. Complexity is risky.",
  "📵 Control: Don’t check PnL mid-trade — manage the trade.",
  "🏃 Exit: Exiting too early is better than exiting too late.",
  "🏗️ Build: Stack good habits — the account will follow.",
  "🎲 Gambling: If you’re guessing, you’re gambling.",
  "🧩 Process: Fall in love with the process, not the outcome.",
  "📛 Burnout: Overtrading is often worse than undertrading.",
  "🎙️ Narrate: If you can’t explain the trade, don’t take it.",
  "🧭 Backtest: Know your edge — test before trust.",
  "🌡️ Risk Check: Don’t size up unless you size down your ego.",
  "🔬 Track: Your edge is only visible if you journal honestly.",
  "🌊 Flow: Let the market come to you — don’t force it.",
  "⛔ Avoid: No trade is better than a bad trade.",
  "🧘‍♂️ Zen: The calmest trader often wins the long game.",
  "🌱 Growth: Small size + consistency = exponential learning.",
];

module.exports = tradingTips;
